services:
  coreai-mcu-knowledge-pgv:
    build:
      context: .
      target: production
    image: coreai-mcu-knowledge-pgv
    container_name: coreai-mcu-knowledge-pgv
    depends_on:
      - coreai-mcu-knowledge-pgv-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-knowledge-pgv-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  coreai-mcu-knowledge-pgv-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: coreai-mcu-knowledge-pgv
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
