namespaceTopics:
  - name: knowledge-ingestion
    roleAssignments:
      - roleName: 'TopicReceiver'
    topicSubscriptions:
      - name: coreai-mcu-knowledge-pgv
postgres:
  db:
    name: core_ai_mcu_knowledge
    charset: UTF8
    collation: en_US.utf8
