namespaceTopics:
  - name: knowledge-ingest
    roleAssignments:
      - roleName: 'TopicReceiver'
    topicSubscriptions:
      - name: knowledge-pgv
postgres:
  db:
    name: knowledge
    charset: UTF8
    collation: en_US.utf8

storageAccounts:
  - name: 'coreaimcu'
    owner: 'no'
    roleAssignments:
      - roleName: 'DataWriter'
    blobContainers:
      - name: 'knowledge'
