namespaceTopics:
  - name: knowledge-ingest
    roleAssignments:
      - roleName: 'TopicReceiver'
    topicSubscriptions:
      - name: coreai-mcu-knowledge-pgv
postgres:
  db:
    name: knowledge
    charset: UTF8
    collation: en_US.utf8
