- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: MESSAGE_QUEUE_HOST
  value: "{{servicename}}-MESSAGE-QUEUE-HOST"
  type: "keyvault"
- key: KNOWLEDGE_INGESTION_PGV_SUBSCRIPTION
  value: "{{servicename}}-INGESTION-SUBSCRIPTION"
  type: "keyvault"
- key: KNOWLEDGE_INGESTION_TOPIC
  value: "{{servicename}}-INGESTION-TOPIC"
  type: "keyvault"
- key: POSTGRES_HOST
  value: "{{servicename}}-POSTGRES-HOST"
  type: "keyvault"
- key: POSTGRES_DB
  value: "coreai-mcu-knowledge"
- key: AZURE_OPENAI_INSTANCE_NAME
  value: "{{servicename}}-AZURE-OPENAI-INSTANCE-NAME"
  type: "keyvault"
- key: AZURE_OPENAI_KEY
  value: "{{servicename}}-AZURE-OPENAI-KEY"
  type: "keyvault"
- key: AZURE_OPENAI_API_VERSION
  value: "2024-02-01"
- key: EMBEDDING_MODEL_NAME
  type: "keyvault"
  value: "{{servicename}}-EMBEDDING-MODEL-NAME"
- key: AZURE_STORAGE_ACCOUNT
  value: "sndadpinfst3401coreaipgv" 
